name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: git@github.com:minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  MANIFEST_BRANCH: twrp-12.1
  DEVICE: OP6xT
  DT_LINK: https://github.com/SIDDK24/TWRP_OP6xT.git
  DT_PATH: device/oneplus/OP6xT
  TARGET: bootimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Recovery Compilation
         uses: SIDDK24/Recovery-Compiler@production

       - name: Uploading SHRP Build
         run: |
              cd ${BuildPath}/out/target/product/${CODENAME}/
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet *SHRP*.zip
              ./transfer wet *Addon*.zip
             
       - uses: actions/upload-artifact@v2
         with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryimage
          path: work/out/target/product/*/*.img

             
             
