name: Building recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  MANIFEST: orangefox11
  MANIFEST_BRANCH: fox_11.0
  DEVICE: OP6xT
  DT_LINK: https://github.com/SIDDK24/OFOX_OP6xT.git
  DT_PATH: device/oneplus/OP6xT
  TARGET: bootimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Recovery Compilation
         uses: SIDDK24/Recovery-Compiler@production
             
       - uses: actions/upload-artifact@v2
         with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip

       - uses: actions/upload-artifact@v2
         with:
          name: recoveryimage
          path: work/out/target/product/*/*.img

             
             
